resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/mesosphere/zookeeper-operator
  newName: testzkop/zookeeper-operator-testimages
  newTag: check
